debug: true
server:
  port: 8081
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db_library:5432/library
    username: library
    password:
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
      ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT: true